name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Test setup
        run: |
          cargo install --git https://github.com/kinpoko/zktc-asm.git
          cargo install --git https://github.com/kinpoko/zktc-emu.git
          sudo apt-get update
          sudo apt-get install expect
      - name: Run tests
        run: make test
